# Generated by Django 5.2.3 on 2025-07-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author'),
        ('core', '0004_clubs_slug_leagues_slug_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clubs'),
        ),
        migrations.AddField(
            model_name='article',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.leagues'),
        ),
        migrations.AddField(
            model_name='article',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player'),
        ),
    ]
