# Generated by Django 5.2.3 on 2025-07-13 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
