# Generated by Django 5.2.3 on 2025-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='eng_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='leagues',
            name='eng_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='eng_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
