# Generated by Django 5.2.3 on 2025-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clubs_eng_name_leagues_eng_name_player_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='leagues',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
