# Generated by Django 5.2.3 on 2025-07-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clubs_slug_leagues_slug_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='core.leagues'),
        ),
    ]
