# Generated by Django 5.2.3 on 2025-07-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_matches_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='core.leagues'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
