# Generated by Django 5.2.3 on 2025-07-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_playerstats_clubs_c_goals_clubs_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('AT', 'Attacker')], max_length=50),
        ),
    ]
