# Generated by Django 5.2.3 on 2025-07-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_leagues_options_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='club', serialize=False, to='core.clubs')),
                ('capacity', models.PositiveIntegerField()),
                ('opened', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
