# Generated by Django 5.2.3 on 2025-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
