# Generated by Django 5.2.3 on 2025-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stadium_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
