# Generated by Django 5.2.3 on 2025-07-29 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_matches_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Вратар'), ('DF', 'Защитник'), ('MF', 'Халф'), ('AT', 'Нападател')], max_length=50),
        ),
    ]
