# Generated by Django 5.2.3 on 2025-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_player_date_of_birth_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='minutes_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
