# Generated by Django 5.2.3 on 2025-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
