# Generated by Django 5.2.3 on 2025-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_quiz_eng_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
