# Generated by Django 5.2.3 on 2025-08-02 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 17, 11, 38, 478152, tzinfo=datetime.timezone.utc)),
        ),
    ]
