# Generated by Django 5.2.3 on 2025-08-02 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_quizattempt_time_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 20, 9, 6, 587262, tzinfo=datetime.timezone.utc)),
        ),
    ]
