# Generated by Django 5.2.3 on 2025-08-02 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_quizattempt_time_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 20, 15, 48, 645452, tzinfo=datetime.timezone.utc)),
        ),
    ]
