# Generated by Django 5.2.3 on 2025-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_quizattempt_time_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
